export interface PortCoord {
  id: string;
  name: string;
  code: string;
  country: string;
  region: "australia" | "uae" | "uk" | "europe" | "usa";
  lat: number;
  lng: number;
  transit: string;
  cost20ft: string;
  cost40ft: string;
  buyerNote: string;
  description: string;
}

export const CHENNAI_ORIGIN = {
  name: "Chennai Export Terminal (Origin)",
  code: "INMAA",
  lat: 13.0827,
  lng: 80.2707,
};

export const GLOBAL_PORTS_DATA: PortCoord[] = [
  // ── AUSTRALIA ──
  {
    id: "perth",
    name: "Perth (Fremantle Port)",
    code: "AUFRE",
    country: "Australia",
    region: "australia",
    lat: -32.0569,
    lng: 115.7439,
    transit: "12–18 days",
    cost20ft: "USD $1,200–$2,000",
    cost40ft: "USD $2,500–$4,500",
    buyerNote: "Closest Australian port to India — fastest ocean transit route.",
    description: "Direct shipping line from Chennai via Sunda Strait to Fremantle Port, serving Perth, Margaret River & WA architectural developments.",
  },
  {
    id: "sydney",
    name: "Sydney (Port Botany)",
    code: "AUSYD",
    country: "Australia",
    region: "australia",
    lat: -33.9500,
    lng: 151.2167,
    transit: "18–22 days",
    cost20ft: "USD $1,500–$2,500",
    cost40ft: "USD $2,500–$4,500",
    buyerNote: "High-frequency weekly container line for NSW commercial & residential builders.",
    description: "Servicing Sydney Metro, Greater Western Sydney, Newcastle, and regional NSW luxury developments via Port Botany.",
  },
  {
    id: "melbourne",
    name: "Melbourne (Port of Melbourne)",
    code: "AUMEL",
    country: "Australia",
    region: "australia",
    lat: -37.8136,
    lng: 144.9631,
    transit: "20–25 days",
    cost20ft: "USD $1,500–$2,500",
    cost40ft: "USD $2,500–$4,500",
    buyerNote: "Key container hub for Victoria, Mornington Peninsula & Geelong landscape architects.",
    description: "Discharging at Port of Melbourne with swift metropolitan container transport across Victoria and commercial precincts.",
  },
  {
    id: "brisbane",
    name: "Brisbane (Port of Brisbane)",
    code: "AUBNE",
    country: "Australia",
    region: "australia",
    lat: -27.4698,
    lng: 153.0251,
    transit: "20–25 days",
    cost20ft: "USD $1,800–$2,800",
    cost40ft: "USD $2,500–$4,500",
    buyerNote: "Ideal for Queensland resort pool pavers, limestone copings & coastal villas.",
    description: "Direct maritime route to Brisbane, Gold Coast, and Sunshine Coast resort developments and residential estates.",
  },

  // ── UAE & MIDDLE EAST ──
  {
    id: "dubai",
    name: "Dubai (Jebel Ali Port)",
    code: "AEJEA",
    country: "UAE",
    region: "uae",
    lat: 25.0113,
    lng: 55.0612,
    transit: "6–9 days",
    cost20ft: "USD $900–$1,400",
    cost40ft: "USD $1,600–$2,600",
    buyerNote: "Shortest international ocean transit corridor with direct daily sailings.",
    description: "Middle East's flagship container terminal providing immediate logistics connectivity to Dubai, Palm Jumeirah, and Sharjah mega-developments.",
  },
  {
    id: "abudhabi",
    name: "Abu Dhabi (Khalifa Port)",
    code: "AEKHL",
    country: "UAE",
    region: "uae",
    lat: 24.8860,
    lng: 54.6730,
    transit: "7–10 days",
    cost20ft: "USD $950–$1,450",
    cost40ft: "USD $1,700–$2,700",
    buyerNote: "Deepwater terminal serving luxury Abu Dhabi villa communities and civic monuments.",
    description: "State-of-the-art automated terminal serving Abu Dhabi capital district, Saadiyat Island, and Yas Island architectural projects.",
  },

  // ── UNITED KINGDOM ──
  {
    id: "felixstowe",
    name: "Felixstowe / London Port",
    code: "GBFXT",
    country: "United Kingdom",
    region: "uk",
    lat: 51.9617,
    lng: 1.3513,
    transit: "20–25 days",
    cost20ft: "USD $1,400–$2,200",
    cost40ft: "USD $2,400–$3,800",
    buyerNote: "UK's primary container gateway with direct rail links to London & the Midlands.",
    description: "Britain's largest and busiest container port, serving London architectural firms, estate developers, and national stone distributors.",
  },
  {
    id: "southampton",
    name: "Southampton Port",
    code: "GBSOU",
    country: "United Kingdom",
    region: "uk",
    lat: 50.9097,
    lng: -1.4044,
    transit: "22–26 days",
    cost20ft: "USD $1,450–$2,250",
    cost40ft: "USD $2,500–$3,900",
    buyerNote: "Strategic South Coast hub for Southern England and Home Counties stone deliveries.",
    description: "Deepwater container hub optimized for rapid offloading and direct road freight across Southern England and Greater London.",
  },

  // ── EUROPE ──
  {
    id: "rotterdam",
    name: "Rotterdam Port",
    code: "NLRTM",
    country: "Netherlands / EU",
    region: "europe",
    lat: 51.9244,
    lng: 4.4777,
    transit: "22–26 days",
    cost20ft: "USD $1,350–$2,100",
    cost40ft: "USD $2,300–$3,700",
    buyerNote: "Europe's biggest ocean port — seamless barge & rail distribution across Germany, France & Benelux.",
    description: "Main European logistics artery handling massive volumes of Indian natural slate, limestone, and granite with bonded EU customs clearance.",
  },
  {
    id: "hamburg",
    name: "Hamburg Port",
    code: "DEHAM",
    country: "Germany / EU",
    region: "europe",
    lat: 53.5511,
    lng: 9.9937,
    transit: "24–28 days",
    cost20ft: "USD $1,450–$2,300",
    cost40ft: "USD $2,500–$3,900",
    buyerNote: "Central Northern European gateway serving German, Austrian & Scandinavian markets.",
    description: "Premier container hub for German commercial cladding contractors and Central European stone wholesalers.",
  },
  {
    id: "genoa",
    name: "Genoa (Port of Genoa)",
    code: "ITGOA",
    country: "Italy / Med EU",
    region: "europe",
    lat: 44.4056,
    lng: 8.9463,
    transit: "16–20 days",
    cost20ft: "USD $1,200–$1,900",
    cost40ft: "USD $2,100–$3,400",
    buyerNote: "Direct Mediterranean route with fast transit through Suez Canal.",
    description: "Strategic Mediterranean seaport serving Italian, Swiss, and Southern European architectural fabricators and monument specialists.",
  },

  // ── UNITED STATES ──
  {
    id: "newyork",
    name: "New York / New Jersey Port",
    code: "USNYC",
    country: "United States",
    region: "usa",
    lat: 40.7128,
    lng: -74.0060,
    transit: "24–30 days",
    cost20ft: "USD $2,200–$3,400",
    cost40ft: "USD $3,600–$5,500",
    buyerNote: "East Coast premier container hub servicing NY, NJ, CT & New England distributors.",
    description: "Direct Atlantic sealane to Port Newark Container Terminal serving luxury residential developments, corporate plazas, and East Coast stone yards.",
  },
  {
    id: "losangeles",
    name: "Los Angeles / Long Beach",
    code: "USLAX",
    country: "United States",
    region: "usa",
    lat: 33.7701,
    lng: -118.1937,
    transit: "22–28 days",
    cost20ft: "USD $2,400–$3,600",
    cost40ft: "USD $3,800–$5,800",
    buyerNote: "West Coast gateway servicing California, Nevada, and Pacific Northwest projects.",
    description: "Pacific ocean routing into America's largest seaport complex, serving California luxury estates, hotel renovations, and landscape architects.",
  },
  {
    id: "houston",
    name: "Houston Port (Port of Houston)",
    code: "USHOU",
    country: "United States",
    region: "usa",
    lat: 29.7604,
    lng: -95.3698,
    transit: "26–32 days",
    cost20ft: "USD $2,500–$3,700",
    cost40ft: "USD $3,900–$6,000",
    buyerNote: "Gulf Coast hub serving Texas, Florida, and central US commercial construction.",
    description: "Direct container corridor through Gulf of Mexico to Bayport and Barbours Cut terminals with extensive intermodal rail connectivity.",
  },
  {
    id: "savannah",
    name: "Savannah Port (Garden City)",
    code: "USSAV",
    country: "United States",
    region: "usa",
    lat: 32.0809,
    lng: -81.0912,
    transit: "25–30 days",
    cost20ft: "USD $2,300–$3,500",
    cost40ft: "USD $3,700–$5,600",
    buyerNote: "Fastest-growing Southeast hub for Georgia, Carolinas, and Florida developments.",
    description: "Dedicated single-terminal facility with exceptional interstate highway access serving Southeastern architectural stone distributors.",
  },
];
